services:
  cliente_mqtt:
    image: clientemqtt
    container_name: cliente_mqtt
    environment:
      - TZ="America/Argentina/Buenos_Aires"
      - SERVIDOR=${SERVIDOR}
      - TOPICO1=${TOPICO1}
      - TOPICO2=${TOPICO2}
      - PUBLICAR=${PUBLICAR}
    restart: unless-stopped